export interface ELStep {
  lineIndex: number;
  callStack: string[];
  microQueue: string[];
  macroQueue: string[];
  log: string[];
  description: string;
}

export interface ELSnippet {
  id: string;
  label: string;
  code: string[];
  steps: ELStep[];
}

const snippet1: ELSnippet = {
  id: 'basic',
  label: 'Sync + Timeout',
  code: [
    'console.log("start");',
    '',
    'setTimeout(() => {',
    '  console.log("timeout");',
    '}, 0);',
    '',
    'console.log("end");',
  ],
  steps: [
    {
      lineIndex: -1,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Программа загружена. Call Stack пуст.',
    },
    {
      lineIndex: 0,
      callStack: ['console.log("start")'],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Вызов console.log("start") попадает в Call Stack.',
    },
    {
      lineIndex: 0,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: ['start'],
      description: 'console.log выполнен → "start" в консоли. Stack очищен.',
    },
    {
      lineIndex: 2,
      callStack: ['setTimeout(cb, 0)'],
      microQueue: [],
      macroQueue: [],
      log: ['start'],
      description: 'setTimeout вызывается. Callback уходит к Web APIs.',
    },
    {
      lineIndex: 2,
      callStack: [],
      microQueue: [],
      macroQueue: ['cb (timeout)'],
      log: ['start'],
      description: 'Web API отдаёт callback в Macrotask Queue.',
    },
    {
      lineIndex: 6,
      callStack: ['console.log("end")'],
      microQueue: [],
      macroQueue: ['cb (timeout)'],
      log: ['start'],
      description: 'console.log("end") в Call Stack.',
    },
    {
      lineIndex: 6,
      callStack: [],
      microQueue: [],
      macroQueue: ['cb (timeout)'],
      log: ['start', 'end'],
      description: '"end" залогировано. Stack снова пуст.',
    },
    {
      lineIndex: 3,
      callStack: ['cb (timeout)'],
      microQueue: [],
      macroQueue: [],
      log: ['start', 'end'],
      description: 'Stack пуст → Event Loop берёт задачу из Macrotask Queue.',
    },
    {
      lineIndex: 3,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: ['start', 'end', 'timeout'],
      description: '"timeout" залогировано. Все очереди пусты. Готово.',
    },
  ],
};

const snippet2: ELSnippet = {
  id: 'promise',
  label: 'Promise vs Timeout',
  code: [
    'console.log("start");',
    '',
    'setTimeout(() => {',
    '  console.log("macro");',
    '}, 0);',
    '',
    'Promise.resolve()',
    '  .then(() => {',
    '    console.log("micro");',
    '  });',
    '',
    'console.log("end");',
  ],
  steps: [
    {
      lineIndex: -1,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Начало выполнения скрипта.',
    },
    {
      lineIndex: 0,
      callStack: ['console.log("start")'],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Синхронный вызов console.log("start").',
    },
    {
      lineIndex: 0,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: ['start'],
      description: '"start" → консоль.',
    },
    {
      lineIndex: 2,
      callStack: ['setTimeout(cb, 0)'],
      microQueue: [],
      macroQueue: [],
      log: ['start'],
      description: 'setTimeout: callback регистрируется в Web APIs.',
    },
    {
      lineIndex: 2,
      callStack: [],
      microQueue: [],
      macroQueue: ['cb (macro)'],
      log: ['start'],
      description: 'Callback попал в Macrotask Queue.',
    },
    {
      lineIndex: 6,
      callStack: ['Promise.resolve().then(cb)'],
      microQueue: [],
      macroQueue: ['cb (macro)'],
      log: ['start'],
      description: 'Promise уже resolved → .then() сразу ставит callback в Microtask Queue.',
    },
    {
      lineIndex: 6,
      callStack: [],
      microQueue: ['cb (micro)'],
      macroQueue: ['cb (macro)'],
      log: ['start'],
      description: 'Microtask Queue получила callback от Promise.then.',
    },
    {
      lineIndex: 11,
      callStack: ['console.log("end")'],
      microQueue: ['cb (micro)'],
      macroQueue: ['cb (macro)'],
      log: ['start'],
      description: 'Синхронный вызов console.log("end").',
    },
    {
      lineIndex: 11,
      callStack: [],
      microQueue: ['cb (micro)'],
      macroQueue: ['cb (macro)'],
      log: ['start', 'end'],
      description: '"end" → консоль. Синхронный стек исчерпан.',
    },
    {
      lineIndex: 8,
      callStack: ['cb (micro)'],
      microQueue: [],
      macroQueue: ['cb (macro)'],
      log: ['start', 'end'],
      description: 'Microtask Queue обрабатывается первой — до следующей macrotask!',
    },
    {
      lineIndex: 8,
      callStack: [],
      microQueue: [],
      macroQueue: ['cb (macro)'],
      log: ['start', 'end', 'micro'],
      description: '"micro" → консоль. Microtask Queue пуста.',
    },
    {
      lineIndex: 3,
      callStack: ['cb (macro)'],
      microQueue: [],
      macroQueue: [],
      log: ['start', 'end', 'micro'],
      description: 'Теперь Event Loop берёт из Macrotask Queue.',
    },
    {
      lineIndex: 3,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: ['start', 'end', 'micro', 'macro'],
      description: '"macro" → консоль. Всё завершено.',
    },
  ],
};

const snippet3: ELSnippet = {
  id: 'nested',
  label: 'Вложенные промисы',
  code: [
    'Promise.resolve()',
    '  .then(() => {',
    '    console.log("micro 1");',
    '    return Promise.resolve();',
    '  })',
    '  .then(() => {',
    '    console.log("micro 2");',
    '  });',
    '',
    'setTimeout(() => {',
    '  console.log("macro");',
    '}, 0);',
  ],
  steps: [
    {
      lineIndex: -1,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Старт. Смотрим, что победит: вложенные микрозадачи или макрозадача?',
    },
    {
      lineIndex: 0,
      callStack: ['Promise.resolve().then(cb1)'],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Первый .then добавляется в Microtask Queue.',
    },
    {
      lineIndex: 0,
      callStack: [],
      microQueue: ['cb1 (micro)'],
      macroQueue: [],
      log: [],
      description: 'cb1 зарегистрирован в Microtask Queue.',
    },
    {
      lineIndex: 9,
      callStack: ['setTimeout(cb_macro, 0)'],
      microQueue: ['cb1 (micro)'],
      macroQueue: [],
      log: [],
      description: 'setTimeout регистрирует macrotask.',
    },
    {
      lineIndex: 9,
      callStack: [],
      microQueue: ['cb1 (micro)'],
      macroQueue: ['cb_macro'],
      log: [],
      description: 'Синхронный код завершён. Начинаем обработку очередей.',
    },
    {
      lineIndex: 2,
      callStack: ['cb1 (micro)'],
      microQueue: [],
      macroQueue: ['cb_macro'],
      log: [],
      description: 'cb1 из Microtask Queue → Call Stack.',
    },
    {
      lineIndex: 2,
      callStack: [],
      microQueue: ['cb2 (micro)'],
      macroQueue: ['cb_macro'],
      log: ['micro 1'],
      description: '"micro 1" залогировано. return Promise.resolve() → cb2 добавлен в Microtask Queue.',
    },
    {
      lineIndex: 6,
      callStack: ['cb2 (micro)'],
      microQueue: [],
      macroQueue: ['cb_macro'],
      log: ['micro 1'],
      description: 'Microtask Queue не пуста — берём cb2. Макрозадача ждёт.',
    },
    {
      lineIndex: 6,
      callStack: [],
      microQueue: [],
      macroQueue: ['cb_macro'],
      log: ['micro 1', 'micro 2'],
      description: '"micro 2" залогировано. Microtask Queue пуста.',
    },
    {
      lineIndex: 10,
      callStack: ['cb_macro'],
      microQueue: [],
      macroQueue: [],
      log: ['micro 1', 'micro 2'],
      description: 'Только теперь Event Loop берёт макрозадачу.',
    },
    {
      lineIndex: 10,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: ['micro 1', 'micro 2', 'macro'],
      description: '"macro" → консоль. Итог: все микрозадачи — перед макрозадачей.',
    },
  ],
};

const snippet4: ELSnippet = {
  id: 'queueMicrotask',
  label: 'queueMicrotask',
  code: [
    'console.log("start");',
    '',
    'queueMicrotask(() => {',
    '  console.log("micro 1");',
    '});',
    '',
    'Promise.resolve()',
    '  .then(() => {',
    '    console.log("promise");',
    '  });',
    '',
    'queueMicrotask(() => {',
    '  console.log("micro 2");',
    '});',
    '',
    'console.log("end");',
  ],
  steps: [
    {
      lineIndex: -1,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'queueMicrotask и Promise — одна очередь. Убедимся.',
    },
    {
      lineIndex: 0,
      callStack: ['console.log("start")'],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Синхронный console.log("start").',
    },
    {
      lineIndex: 0,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: ['start'],
      description: '"start" → консоль.',
    },
    {
      lineIndex: 2,
      callStack: ['queueMicrotask(cb1)'],
      microQueue: [],
      macroQueue: [],
      log: ['start'],
      description: 'queueMicrotask регистрирует cb1 в Microtask Queue напрямую.',
    },
    {
      lineIndex: 2,
      callStack: [],
      microQueue: ['cb1 (micro)'],
      macroQueue: [],
      log: ['start'],
      description: 'cb1 зарегистрирован.',
    },
    {
      lineIndex: 6,
      callStack: ['Promise.resolve().then(cb_p)'],
      microQueue: ['cb1 (micro)'],
      macroQueue: [],
      log: ['start'],
      description: 'Promise.resolve() → .then() добавляет cb_p в ту же Microtask Queue.',
    },
    {
      lineIndex: 6,
      callStack: [],
      microQueue: ['cb1 (micro)', 'cb_p (promise)'],
      macroQueue: [],
      log: ['start'],
      description: 'cb_p встаёт за cb1 — очередь FIFO.',
    },
    {
      lineIndex: 12,
      callStack: ['queueMicrotask(cb2)'],
      microQueue: ['cb1 (micro)', 'cb_p (promise)'],
      macroQueue: [],
      log: ['start'],
      description: 'Второй queueMicrotask добавляет cb2 в конец очереди.',
    },
    {
      lineIndex: 12,
      callStack: [],
      microQueue: ['cb1 (micro)', 'cb_p (promise)', 'cb2 (micro)'],
      macroQueue: [],
      log: ['start'],
      description: 'Три задачи в Microtask Queue — в порядке регистрации.',
    },
    {
      lineIndex: 16,
      callStack: ['console.log("end")'],
      microQueue: ['cb1 (micro)', 'cb_p (promise)', 'cb2 (micro)'],
      macroQueue: [],
      log: ['start'],
      description: 'console.log("end") — последний синхронный вызов.',
    },
    {
      lineIndex: 16,
      callStack: [],
      microQueue: ['cb1 (micro)', 'cb_p (promise)', 'cb2 (micro)'],
      macroQueue: [],
      log: ['start', 'end'],
      description: '"end" → консоль. Синхронный стек пуст.',
    },
    {
      lineIndex: 3,
      callStack: ['cb1 (micro)'],
      microQueue: ['cb_p (promise)', 'cb2 (micro)'],
      macroQueue: [],
      log: ['start', 'end'],
      description: 'Event Loop обрабатывает Microtask Queue — первый cb1.',
    },
    {
      lineIndex: 3,
      callStack: [],
      microQueue: ['cb_p (promise)', 'cb2 (micro)'],
      macroQueue: [],
      log: ['start', 'end', 'micro 1'],
      description: '"micro 1" залогировано.',
    },
    {
      lineIndex: 8,
      callStack: ['cb_p (promise)'],
      microQueue: ['cb2 (micro)'],
      macroQueue: [],
      log: ['start', 'end', 'micro 1'],
      description: 'Следующий — cb_p из Promise.then.',
    },
    {
      lineIndex: 8,
      callStack: [],
      microQueue: ['cb2 (micro)'],
      macroQueue: [],
      log: ['start', 'end', 'micro 1', 'promise'],
      description: '"promise" залогировано.',
    },
    {
      lineIndex: 13,
      callStack: ['cb2 (micro)'],
      microQueue: [],
      macroQueue: [],
      log: ['start', 'end', 'micro 1', 'promise'],
      description: 'Последний — cb2 из второго queueMicrotask.',
    },
    {
      lineIndex: 13,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: ['start', 'end', 'micro 1', 'promise', 'micro 2'],
      description: 'Итог: queueMicrotask и Promise.then попадают в одну очередь, порядок — FIFO.',
    },
  ],
};

const snippet5: ELSnippet = {
  id: 'macro-seeds-micro',
  label: 'Макро → Микро',
  code: [
    'setTimeout(() => {',
    '  console.log("macro 1");',
    '  Promise.resolve()',
    '    .then(() => {',
    '      console.log("micro from macro 1");',
    '    });',
    '}, 0);',
    '',
    'setTimeout(() => {',
    '  console.log("macro 2");',
    '}, 0);',
  ],
  steps: [
    {
      lineIndex: -1,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Две макрозадачи. Первая внутри себя порождает микрозадачу. Что будет?',
    },
    {
      lineIndex: 0,
      callStack: ['setTimeout(cb1, 0)'],
      microQueue: [],
      macroQueue: [],
      log: [],
      description: 'Первый setTimeout регистрируется в Web API.',
    },
    {
      lineIndex: 0,
      callStack: [],
      microQueue: [],
      macroQueue: ['cb1 (macro 1)'],
      log: [],
      description: 'cb1 → Macrotask Queue.',
    },
    {
      lineIndex: 8,
      callStack: ['setTimeout(cb2, 0)'],
      microQueue: [],
      macroQueue: ['cb1 (macro 1)'],
      log: [],
      description: 'Второй setTimeout регистрируется.',
    },
    {
      lineIndex: 8,
      callStack: [],
      microQueue: [],
      macroQueue: ['cb1 (macro 1)', 'cb2 (macro 2)'],
      log: [],
      description: 'cb2 → Macrotask Queue. Синхронный код закончился.',
    },
    {
      lineIndex: 1,
      callStack: ['cb1 (macro 1)'],
      microQueue: [],
      macroQueue: ['cb2 (macro 2)'],
      log: [],
      description: 'Event Loop берёт ПЕРВУЮ макрозадачу: cb1.',
    },
    {
      lineIndex: 2,
      callStack: ['cb1 (macro 1)', 'Promise.resolve().then(p_cb)'],
      microQueue: [],
      macroQueue: ['cb2 (macro 2)'],
      log: ['macro 1'],
      description: '"macro 1" залогировано. Promise.then внутри cb1 → p_cb в Microtask Queue.',
    },
    {
      lineIndex: 2,
      callStack: [],
      microQueue: ['p_cb (micro)'],
      macroQueue: ['cb2 (macro 2)'],
      log: ['macro 1'],
      description: 'cb1 завершён. В Microtask Queue — p_cb. cb2 всё ещё ждёт.',
    },
    {
      lineIndex: 4,
      callStack: ['p_cb (micro)'],
      microQueue: [],
      macroQueue: ['cb2 (macro 2)'],
      log: ['macro 1'],
      description: 'КЛЮЧЕВОЙ МОМЕНТ: до cb2 Event Loop сначала обрабатывает все микрозадачи.',
    },
    {
      lineIndex: 4,
      callStack: [],
      microQueue: [],
      macroQueue: ['cb2 (macro 2)'],
      log: ['macro 1', 'micro from macro 1'],
      description: '"micro from macro 1" залогировано. Только теперь Microtask Queue пуста.',
    },
    {
      lineIndex: 9,
      callStack: ['cb2 (macro 2)'],
      microQueue: [],
      macroQueue: [],
      log: ['macro 1', 'micro from macro 1'],
      description: 'Event Loop берёт вторую макрозадачу: cb2.',
    },
    {
      lineIndex: 9,
      callStack: [],
      microQueue: [],
      macroQueue: [],
      log: ['macro 1', 'micro from macro 1', 'macro 2'],
      description: '"macro 2" залогировано. Итог: микрозадача из macro 1 выполнилась перед macro 2.',
    },
  ],
};

export const snippets: ELSnippet[] = [snippet1, snippet2, snippet3, snippet4, snippet5];
