import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  { id: 'sort-1', difficulty: 'easy', question: 'Какова сложность Bubble Sort в худшем случае?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], correct: 2, explanation: 'Два вложенных цикла: внешний n итераций, внутренний до n. Итого O(n²).' },
  { id: 'sort-2', difficulty: 'easy', question: 'Какова сложность Merge Sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], correct: 1, explanation: 'log n уровней рекурсии (деление пополам) × O(n) для слияния на каждом уровне = O(n log n).' },
  { id: 'sort-3', difficulty: 'medium', question: 'Merge Sort требует дополнительной памяти:', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], correct: 2, explanation: 'При слиянии нужен временный массив размером O(n). Это основной недостаток Merge Sort по сравнению с Quick Sort.' },
  { id: 'sort-4', difficulty: 'medium', question: 'Quick Sort в среднем работает за O(n log n), но в худшем случае:', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'], correct: 2, explanation: 'Худший случай — уже отсортированный массив с плохим выбором pivot (первый/последний элемент). Рекурсия идёт на n уровней вглубь.' },
  { id: 'sort-5', difficulty: 'hard', question: 'Почему в реальных языках (V8, Java) часто используют TimSort?', options: ['Он проще реализуется', 'Сочетает Merge Sort и Insertion Sort, быстр на реальных данных с частично отсортированными участками', 'Лучшая worst-case сложность', 'Использует меньше памяти'], correct: 1, explanation: 'TimSort находит натурально отсортированные "runs", дополняет до минимального размера insertion sort и сливает. Реальные данные часто частично упорядочены.' },
  { id: 'sort-6', difficulty: 'easy', question: 'Insertion Sort хорош для:', options: ['Больших случайных массивов', 'Малых или почти отсортированных массивов', 'Числовых массивов с малым диапазоном', 'Стабильной сортировки больших данных'], correct: 1, explanation: 'При почти отсортированном массиве Insertion Sort работает за O(n) — почти нет сдвигов. Overhead у сложных алгоритмов не оправдывает себя для малых n.' },
  { id: 'sort-7', difficulty: 'medium', question: 'Что значит "стабильная сортировка"?', options: ['Всегда O(n log n)', 'Элементы с равными ключами сохраняют исходный относительный порядок', 'Не модифицирует исходный массив', 'Работает для любых типов данных'], correct: 1, explanation: 'Стабильность: если a[i] == a[j] и i < j до сортировки, то i < j и после. Merge Sort стабилен, Quick Sort — нет.' },
  { id: 'sort-8', difficulty: 'hard', question: 'Counting Sort работает за O(n + k). Когда он лучше O(n log n) сортировок?', options: ['Всегда', 'Когда k (диапазон значений) << n', 'Только для строк', 'Никогда'], correct: 1, explanation: 'Counting Sort: создаём массив счётчиков размером k. Если k << n (например, оценки 1-100 для 1M студентов), это быстрее O(n log n).' },
  { id: 'sort-9', difficulty: 'medium', question: 'Quick Sort: как случайный выбор pivot помогает?', options: ['Никак', 'Исключает детерминированно плохие случаи, делает O(n²) маловероятным', 'Ускоряет лучший случай', 'Уменьшает использование памяти'], correct: 1, explanation: 'Rand pivot — злоумышленник не может специально подать данные, ухудшающие pivot. Ожидаемая сложность O(n log n) даже на отсортированных данных.' },
  { id: 'sort-10', difficulty: 'easy', question: 'Selection Sort всегда делает ровно n-1 перестановок. Это:', options: ['Делает его быстрее других', 'Полезно когда запись дорогостоящая (например, flash-память)', 'Делает его стабильным', 'Позволяет работать за O(n)'], correct: 1, explanation: 'n-1 свопов — минимум среди сравнительных сортировок. Это важно когда swap дорог (запись в энергонезависимую память).' },
  { id: 'sort-11', difficulty: 'hard', question: 'Нижняя граница для сортировки сравнением — Ω(n log n). Почему нельзя быстрее?', options: ['Физическое ограничение процессора', 'Дерево решений имеет n! листьев, высота ≥ log₂(n!) ≈ n log n', 'Из-за кеш-промахов', 'Теорема Гёделя'], correct: 1, explanation: 'Для n элементов — n! возможных порядков. Каждое сравнение даёт 1 бит. Минимальная глубина бинарного дерева с n! листьями = ⌈log₂(n!)⌉ ≈ n log n.' },
  { id: 'sort-12', difficulty: 'medium', question: 'В каком случае Bubble Sort работает за O(n)?', options: ['Всегда', 'Когда массив уже отсортирован (с оптимизацией флага)', 'Когда все элементы одинаковые', 'Никогда'], correct: 1, explanation: 'С флагом swapped: если за один проход не было ни одного свопа — массив отсортирован, выходим. Для уже отсортированного — один проход O(n).' },
  { id: 'sort-13', difficulty: 'medium', question: 'Heap Sort: пространственная сложность?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'], correct: 2, explanation: 'Heap Sort сортирует in-place, используя только O(1) дополнительной памяти (не считая стека рекурсии). В отличие от Merge Sort с O(n).' },
  { id: 'sort-14', difficulty: 'easy', question: 'Какой алгоритм использует принцип "разделяй и властвуй"?', options: ['Bubble Sort', 'Selection Sort', 'Merge Sort', 'Counting Sort'], correct: 2, explanation: 'Merge Sort делит массив пополам (разделяй), рекурсивно сортирует (властвуй), затем сливает (комбинируй).' },
  { id: 'sort-15', difficulty: 'hard', question: 'Radix Sort: сложность для n чисел с d цифрами по основанию b?', options: ['O(n log n)', 'O(dn)', 'O(n²)', 'O(d × n log n)'], correct: 1, explanation: 'Radix Sort делает d проходов, каждый — стабильная сортировка по одной цифре за O(n + b). Итого O(d(n + b)). При фиксированных d и b — O(n), не зависит от log n.' },
];
