import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ── SELECT basics ────────────────────────────────────────────────────────────
  {
    id: 'sql-1',
    difficulty: 'easy',
    code: '',
    question: 'Какой результат вернёт запрос: SELECT * FROM users WHERE 1 = 0 ?',
    options: [
      'Все строки таблицы users',
      'Синтаксическую ошибку: нельзя сравнивать числа',
      'Пустой результат: ни одна строка не удовлетворяет условию',
      'NULL во всех ячейках',
    ],
    correct: 2,
    explanation: 'WHERE 1 = 0 всегда ложно, поэтому ни одна строка не пройдёт фильтр. Результат — пустая таблица с нужными колонками. Это легальный SQL, часто используется для получения только структуры.',
  },
  {
    id: 'sql-2',
    difficulty: 'easy',
    code: '',
    question: 'Как получить только уникальные значения поля city из таблицы users?',
    options: [
      'SELECT UNIQUE city FROM users',
      'SELECT city FROM users GROUP BY city HAVING DISTINCT city',
      'SELECT DISTINCT city FROM users',
      'SELECT city FROM users WHERE UNIQUE = true',
    ],
    correct: 2,
    explanation: 'DISTINCT убирает дубли из результата. Можно также GROUP BY city, но DISTINCT — прямой и понятный способ.',
  },
  {
    id: 'sql-3',
    difficulty: 'easy',
    code: "SELECT name FROM users\nORDER BY salary DESC\nLIMIT 3",
    question: 'Что вернёт этот запрос?',
    options: [
      'Три сотрудника с минимальной зарплатой',
      'Три сотрудника с максимальной зарплатой',
      'Три первых сотрудника в алфавитном порядке',
      'Сотрудников, у которых salary = NULL',
    ],
    correct: 1,
    explanation: 'ORDER BY salary DESC сортирует от большего к меньшему, LIMIT 3 берёт первые три строки. Итого — три сотрудника с наибольшими зарплатами.',
  },
  {
    id: 'sql-4',
    difficulty: 'easy',
    code: "SELECT * FROM users\nWHERE dept_id = NULL",
    question: 'Почему этот запрос НЕ вернёт сотрудников без отдела?',
    options: [
      'Синтаксическая ошибка: нельзя использовать = с NULL',
      'Сравнение с NULL через = всегда возвращает unknown, не true',
      'NULL означает пустую строку, а не отсутствие значения',
      'Нужно писать dept_id == NULL с двойным равенством',
    ],
    correct: 1,
    explanation: 'В SQL любое сравнение с NULL возвращает unknown (не true и не false). Поэтому WHERE dept_id = NULL не найдёт ничего. Правильно: WHERE dept_id IS NULL.',
  },

  // ── Aggregates ────────────────────────────────────────────────────────────────
  {
    id: 'sql-5',
    difficulty: 'easy',
    code: "SELECT COUNT(*) FROM orders\nWHERE status = 'done'",
    question: 'Что считает COUNT(*) в этом запросе?',
    options: [
      'Количество уникальных значений в таблице orders',
      'Количество столбцов в таблице orders',
      'Количество строк, где status = done',
      'Сумму всех значений amount, где status = done',
    ],
    correct: 2,
    explanation: 'COUNT(*) считает количество строк. После WHERE status = \'done\' остаются только выполненные заказы, их и считаем. COUNT(*) не пропускает NULL-строки в отличие от COUNT(col).',
  },
  {
    id: 'sql-6',
    difficulty: 'medium',
    code: "SELECT COUNT(dept_id) FROM users",
    question: 'Чем COUNT(dept_id) отличается от COUNT(*) для таблицы users, где у Henry dept_id = NULL?',
    options: [
      'COUNT(dept_id) = 8, COUNT(*) = 7 — NULL считается как 0',
      'COUNT(dept_id) = 7, COUNT(*) = 8 — COUNT(col) не учитывает NULL',
      'Результат одинаков: оба вернут 8',
      'COUNT(dept_id) вызовет ошибку для NULL-значений',
    ],
    correct: 1,
    explanation: 'COUNT(*) считает все строки включая NULL. COUNT(col) считает только строки, где col не NULL. У Henry dept_id = NULL, поэтому COUNT(dept_id) = 7, COUNT(*) = 8.',
  },
  {
    id: 'sql-7',
    difficulty: 'medium',
    code: "SELECT city, AVG(salary)\nFROM users\nGROUP BY city\nHAVING AVG(salary) > 100000",
    question: 'В чём разница между HAVING и WHERE в этом запросе?',
    options: [
      'WHERE фильтрует строки до агрегации, HAVING — группы после агрегации',
      'HAVING заменяет WHERE когда есть GROUP BY — они взаимозаменяемы',
      'WHERE работает с именованными колонками, HAVING — с агрегатами',
      'HAVING выполняется до GROUP BY, WHERE — после него',
    ],
    correct: 0,
    explanation: 'WHERE фильтрует отдельные строки ДО группировки (к агрегатам не применимо). HAVING фильтрует группы ПОСЛЕ агрегации. В этом запросе нельзя написать WHERE AVG(salary) > 100000 — WHERE не умеет работать с агрегатными функциями.',
  },
  {
    id: 'sql-8',
    difficulty: 'medium',
    code: "SELECT dept_id, name, MAX(salary)\nFROM users\nGROUP BY dept_id",
    question: 'Почему этот запрос вызовет ошибку в строгом SQL (PostgreSQL)?',
    options: [
      'MAX(salary) нельзя использовать с GROUP BY',
      'Колонка name не входит в GROUP BY и не является агрегатом',
      'dept_id содержит NULL, что запрещено в GROUP BY',
      'Синтаксическая ошибка: после GROUP BY должен идти ORDER BY',
    ],
    correct: 1,
    explanation: 'В GROUP BY запросе все колонки в SELECT должны либо быть в GROUP BY, либо быть агрегатными функциями. name не входит ни туда, ни туда — SQL не знает, значение какой строки взять для этой колонки внутри группы.',
  },

  // ── JOIN ──────────────────────────────────────────────────────────────────────
  {
    id: 'sql-9',
    difficulty: 'medium',
    code: "SELECT u.name, o.product\nFROM users u\nJOIN orders o ON u.id = o.user_id",
    question: 'Сколько строк вернёт этот INNER JOIN, если у Alice (id=1) два заказа?',
    options: [
      'По одной строке на каждого пользователя — 8 строк',
      'По одной строке на каждый заказ с NULL для пользователей без заказов',
      'По одной строке на каждую пару совпадений — Alice появится дважды',
      'Только строки, где заказ ровно один',
    ],
    correct: 2,
    explanation: 'INNER JOIN создаёт строку для каждой совпадающей пары. У Alice 2 заказа → она появится в результате 2 раза. У Dave и Henry нет заказов → они не появятся вовсе.',
  },
  {
    id: 'sql-10',
    difficulty: 'medium',
    code: '',
    question: 'Чем LEFT JOIN отличается от INNER JOIN?',
    options: [
      'LEFT JOIN быстрее, INNER JOIN надёжнее',
      'LEFT JOIN включает все строки из левой таблицы, даже без совпадений справа (NULL)',
      'LEFT JOIN работает только со строками, INNER JOIN — с числами',
      'LEFT JOIN соединяет по первой колонке, INNER JOIN — по указанной в ON',
    ],
    correct: 1,
    explanation: 'LEFT JOIN гарантирует, что все строки из левой (первой) таблицы попадут в результат. Если совпадения в правой таблице нет, колонки правой таблицы будут NULL. INNER JOIN исключает строки без совпадений с обеих сторон.',
  },
  {
    id: 'sql-11',
    difficulty: 'hard',
    code: "SELECT u.name, COUNT(o.id)\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.name",
    question: 'Что вернёт COUNT(o.id) для пользователей без заказов (Dave, Henry)?',
    options: [
      'NULL — нет данных для агрегации',
      '0 — COUNT(col) возвращает 0 когда col = NULL',
      '1 — строка всё равно существует в результате LEFT JOIN',
      'Ошибку — нельзя считать NULL-значения',
    ],
    correct: 1,
    explanation: 'При LEFT JOIN строки без совпадений получают NULL в колонках правой таблицы. COUNT(o.id) не считает NULL, поэтому вернёт 0. Если бы было COUNT(*), вернуло бы 1 (строка существует). Поэтому для подсчёта связанных записей используют COUNT(правая_таблица.id).',
  },

  // ── Subqueries / CTEs ─────────────────────────────────────────────────────────
  {
    id: 'sql-12',
    difficulty: 'hard',
    code: "SELECT name FROM users\nWHERE salary > (\n  SELECT AVG(salary) FROM users\n)",
    question: 'Что делает подзапрос в WHERE?',
    options: [
      'Фильтрует пользователей по городу с максимальной средней зарплатой',
      'Вычисляет среднюю зарплату один раз и сравнивает каждую строку с ней',
      'Создаёт список всех зарплат для поиска по IN',
      'Группирует пользователей по зарплате выше среднего',
    ],
    correct: 1,
    explanation: 'Подзапрос SELECT AVG(salary) FROM users вычисляется один раз и возвращает скалярное значение (одно число — среднюю зарплату). Затем внешний запрос сравнивает каждую строку с этим числом. Это скалярный подзапрос.',
  },
  {
    id: 'sql-13',
    difficulty: 'hard',
    code: "WITH top_earners AS (\n  SELECT * FROM users\n  WHERE salary > 100000\n)\nSELECT city, COUNT(*) FROM top_earners\nGROUP BY city",
    question: 'Что такое CTE (WITH clause) и зачем он нужен?',
    options: [
      'Постоянная таблица, которая сохраняется в базе после выполнения запроса',
      'Именованный временный результат запроса, доступный внутри основного запроса',
      'Шифрование данных перед чтением из таблицы',
      'Кэш для ускорения повторных запросов к одной таблице',
    ],
    correct: 1,
    explanation: 'CTE (Common Table Expression) — именованный временный результат, существующий только во время выполнения запроса. Делает сложные запросы читаемыми: вместо вложенных подзапросов — именованные блоки. top_earners здесь — это просто отфильтрованный набор строк.',
  },

  // ── Indexes / Performance ─────────────────────────────────────────────────────
  {
    id: 'sql-14',
    difficulty: 'medium',
    code: '',
    question: 'Почему запрос SELECT * FROM users WHERE LOWER(name) = \'alice\' НЕ использует индекс на name?',
    options: [
      'LOWER() — это зарезервированное слово, которое нельзя использовать в WHERE',
      'Индексы на текстовые поля в PostgreSQL не поддерживаются',
      'Функция LOWER изменяет индексируемое значение — база не может использовать B-tree индекс',
      'WHERE должен сравнивать только числовые колонки для использования индекса',
    ],
    correct: 2,
    explanation: 'B-tree индекс хранит оригинальные значения. Когда мы применяем LOWER() к колонке в WHERE, база не знает, что индексированное значение соответствует LOWER(name). Решение: функциональный индекс CREATE INDEX ON users (LOWER(name)) или ILIKE оператор.',
  },
  {
    id: 'sql-15',
    difficulty: 'hard',
    code: "EXPLAIN SELECT * FROM users WHERE salary > 100000",
    question: 'Что покажет EXPLAIN для этого запроса при отсутствии индекса на salary?',
    options: [
      'Index Scan — база всегда использует индекс для числовых сравнений',
      'Hash Join — salary хэшируется для быстрого поиска',
      'Seq Scan — база последовательно читает все строки таблицы',
      'Bitmap Scan — условие > всегда использует bitmap-индекс',
    ],
    correct: 2,
    explanation: 'Seq Scan (Sequential Scan) — полное сканирование таблицы. Без индекса база читает каждую строку и проверяет условие. Это O(n). После CREATE INDEX ON users(salary), EXPLAIN покажет Index Scan — O(log n).',
  },

  // ── Window functions ──────────────────────────────────────────────────────────
  {
    id: 'sql-16',
    difficulty: 'hard',
    code: "SELECT name, salary,\n  RANK() OVER (ORDER BY salary DESC) AS rnk\nFROM users",
    question: 'Чем RANK() отличается от ROW_NUMBER() в оконных функциях?',
    options: [
      'RANK() быстрее, ROW_NUMBER() точнее при больших данных',
      'RANK() даёт одинаковый ранг при равных значениях с пропуском следующего, ROW_NUMBER() — всегда уникален',
      'ROW_NUMBER() работает только с числами, RANK() — с любыми типами данных',
      'Разницы нет — оба дают последовательные уникальные номера',
    ],
    correct: 1,
    explanation: 'При одинаковой зарплате: RANK() даст обоим место 2, следующий получит 4 (пропуск). DENSE_RANK() тоже даст 2, но следующий получит 3 (без пропуска). ROW_NUMBER() всегда уникален — у двух одинаковых зарплат будет 2 и 3 в произвольном порядке.',
  },

  // ── Tricky SQL ────────────────────────────────────────────────────────────────
  {
    id: 'sql-17',
    difficulty: 'medium',
    code: "SELECT name FROM users\nWHERE name LIKE '%a%'",
    question: 'Что вернёт этот запрос?',
    options: [
      'Имена, начинающиеся на букву a',
      'Имена, заканчивающиеся на букву a',
      'Имена, содержащие букву a в любой позиции',
      'Имена из ровно одной буквы a',
    ],
    correct: 2,
    explanation: 'В LIKE: % означает любое количество любых символов (в том числе ноль). %a% означает: любые символы, потом a, потом любые символы — то есть a в любой позиции. Для начала: \'a%\', для конца: \'%a\'.',
  },
  {
    id: 'sql-18',
    difficulty: 'medium',
    code: "SELECT name, salary\nFROM users\nORDER BY 2 DESC",
    question: 'Что означает ORDER BY 2 в этом запросе?',
    options: [
      'Сортировка по второй таблице в FROM',
      'Сортировка по второй колонке в SELECT (salary)',
      'Сортировка по id = 2',
      'Сортировка с шагом 2 (каждая вторая строка)',
    ],
    correct: 1,
    explanation: 'ORDER BY можно задавать по номеру позиции в SELECT-списке. ORDER BY 2 — это ORDER BY salary, потому что salary стоит на второй позиции в SELECT. Лучше явно писать имя колонки для читаемости.',
  },
  {
    id: 'sql-19',
    difficulty: 'hard',
    code: "SELECT name FROM users\nWHERE dept_id NOT IN (1, 2, NULL)",
    question: 'Почему этот запрос вернёт пустой результат, хотя есть сотрудники с dept_id = 3?',
    options: [
      'NOT IN не работает с несколькими значениями в списке',
      'dept_id = 3 автоматически приравнивается к NULL при NOT IN',
      'NOT IN с NULL в списке: 3 NOT IN (..., NULL) = unknown, строки не возвращаются',
      'Ошибка синтаксиса: нельзя смешивать числа и NULL в IN',
    ],
    correct: 2,
    explanation: 'NOT IN (1, 2, NULL) для каждой строки проверяет "3 != 1 AND 3 != 2 AND 3 != NULL". Последнее даёт UNKNOWN. AND с UNKNOWN = UNKNOWN. WHERE UNKNOWN = не добавить строку. Решение: WHERE dept_id NOT IN (1, 2) AND dept_id IS NOT NULL.',
  },
  {
    id: 'sql-20',
    difficulty: 'hard',
    code: "DELETE FROM users\nWHERE id IN (\n  SELECT id FROM users\n  WHERE salary < 80000\n)",
    question: 'Почему этот запрос может не работать в некоторых СУБД?',
    options: [
      'DELETE не поддерживает подзапросы ни в одной СУБД',
      'Нельзя читать таблицу в подзапросе той же таблицы, которую изменяем',
      'IN работает только с константами, не с подзапросами',
      'salary < 80000 синтаксически некорректно в DELETE',
    ],
    correct: 1,
    explanation: 'В некоторых СУБД (MySQL) нельзя читать и изменять одну таблицу в одном запросе. PostgreSQL позволяет это через CTE: WITH to_delete AS (SELECT id FROM users WHERE salary < 80000) DELETE FROM users WHERE id IN (SELECT id FROM to_delete).',
  },
  {
    id: 'sql-21',
    difficulty: 'easy',
    code: '',
    question: 'В какой последовательности база данных логически выполняет SELECT запрос?',
    options: [
      'SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY → LIMIT',
      'FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT',
      'FROM → SELECT → WHERE → GROUP BY → ORDER BY → HAVING → LIMIT',
      'WHERE → FROM → SELECT → GROUP BY → HAVING → ORDER BY → LIMIT',
    ],
    correct: 1,
    explanation: 'Логический порядок: FROM (строим набор строк) → WHERE (фильтруем строки) → GROUP BY (группируем) → HAVING (фильтруем группы) → SELECT (проецируем колонки) → ORDER BY (сортируем) → LIMIT (ограничиваем). Именно поэтому нельзя использовать алиасы из SELECT в WHERE — WHERE выполняется раньше.',
  },
  {
    id: 'sql-22',
    difficulty: 'medium',
    code: "SELECT u.name, d.title\nFROM users u\nJOIN departments d ON u.dept_id = d.id\nWHERE u.salary > 100000",
    question: 'Зачем использовать псевдонимы таблиц (u, d) в этом запросе?',
    options: [
      'Без псевдонимов запрос не работает при использовании JOIN',
      'Псевдонимы ускоряют запрос за счёт кэширования имён таблиц',
      'Псевдонимы сокращают запись и помогают различить одинаковые колонки разных таблиц',
      'Псевдонимы обязательны при использовании WHERE после JOIN',
    ],
    correct: 2,
    explanation: 'Псевдонимы (aliases) — удобство: короче писать u.name вместо users.name. При JOIN из нескольких таблиц с одинаковыми именами колонок (например, id) они необходимы для различения: u.id vs d.id. Без них пришлось бы писать полное имя таблицы.',
  },
];
