import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [

  // ── Основы ────────────────────────────────────────────────────────────────────

  {
    id: 'join-1',
    difficulty: 'easy',
    question: 'Что возвращает INNER JOIN?',
    options: [
      'Только строки, для которых нашлось совпадение в обеих таблицах',
      'Все строки левой таблицы и совпавшие строки правой',
      'Все строки обеих таблиц независимо от совпадений',
      'Только строки, которых нет в другой таблице',
    ],
    correct: 0,
    explanation: 'INNER JOIN — пересечение: строка попадает в результат только если для неё нашлось совпадение по условию ON в обеих таблицах.',
    code: '',
  },
  {
    id: 'join-2',
    difficulty: 'easy',
    question: 'Что происходит с несовпавшими строками при LEFT JOIN?',
    options: [
      'Строки левой таблицы сохраняются, правые колонки заполняются NULL',
      'Строки отбрасываются как при INNER JOIN',
      'Строки правой таблицы сохраняются с NULL слева',
      'Возникает ошибка',
    ],
    correct: 0,
    explanation: 'LEFT JOIN сохраняет ВСЕ строки левой таблицы. Если для строки нет совпадения в правой таблице — колонки правой заполняются NULL.',
    code: '',
  },
  {
    id: 'join-3',
    difficulty: 'easy',
    question: 'Таблица A: 5 строк, таблица B: 4 строки. CROSS JOIN вернёт сколько строк?',
    options: [
      '20',
      '9',
      '5',
      'Зависит от условия ON',
    ],
    correct: 0,
    explanation: 'CROSS JOIN — декартово произведение: каждая строка A соединяется с каждой строкой B. 5 × 4 = 20. У CROSS JOIN нет условия ON.',
    code: 'SELECT * FROM a CROSS JOIN b;  -- 5 × 4 = 20 строк',
  },
  {
    id: 'join-4',
    difficulty: 'medium',
    question: 'В чём разница COUNT(*) и COUNT(o.id) при LEFT JOIN?',
    code: 'SELECT u.name, COUNT(*) AS c1, COUNT(o.id) AS c2\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.name',
    options: [
      'COUNT(*) считает строки с NULL справа как 1, COUNT(o.id) возвращает 0 при отсутствии заказов',
      'Разницы нет — оба возвращают одинаковый результат',
      'COUNT(o.id) считает NULL как 1, COUNT(*) игнорирует NULL',
      'COUNT(*) вызовет ошибку при NULL',
    ],
    correct: 0,
    explanation: 'Когда LEFT JOIN не находит совпадения, строка добавляется с NULL в колонках правой таблицы. COUNT(*) считает эту строку (она есть), COUNT(o.id) игнорирует NULL → возвращает 0.',
  },
  {
    id: 'join-5',
    difficulty: 'medium',
    question: 'Как найти строки из таблицы A, которых нет в таблице B (anti-join)?',
    options: [
      'LEFT JOIN B + WHERE B.id IS NULL',
      'INNER JOIN B + WHERE B.id IS NOT NULL',
      'RIGHT JOIN B + WHERE A.id IS NULL',
      'FULL OUTER JOIN + WHERE A.id IS NULL AND B.id IS NULL',
    ],
    correct: 0,
    explanation: 'Anti-join: LEFT JOIN добавит NULL справа для строк без совпадения. WHERE B.id IS NULL оставит только такие строки. Альтернатива: NOT EXISTS или NOT IN (но NOT IN опасен с NULL).',
    code: 'SELECT u.name\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE o.id IS NULL  -- только те, у кого нет заказов',
  },
  {
    id: 'join-6',
    difficulty: 'easy',
    question: 'Имеет ли значение порядок таблиц в INNER JOIN?',
    options: [
      'Нет — результат одинаков, меняется только потенциальная производительность',
      'Да — левая таблица должна быть меньше',
      'Да — результат будет разным',
      'Да — правая таблица всегда должна содержать больше строк',
    ],
    correct: 0,
    explanation: 'INNER JOIN коммутативен: A INNER JOIN B ≡ B INNER JOIN A. Оптимизатор сам решит порядок соединения. Для LEFT JOIN порядок критичен — он определяет, чьи строки сохраняются.',
    code: '',
  },
  {
    id: 'join-7',
    difficulty: 'medium',
    question: 'LEFT JOIN: изменится ли результат если поменять таблицы местами?',
    options: [
      'Да — изменится, которая сторона "сохраняется"',
      'Нет — результат идентичен',
      'Да — LEFT JOIN превратится в INNER JOIN',
      'Нет — SQL оптимизирует автоматически',
    ],
    correct: 0,
    explanation: 'A LEFT JOIN B ≠ B LEFT JOIN A. В первом — сохраняются все строки A. Во втором — сохраняются все строки B. Это эквивалентно B RIGHT JOIN A.',
    code: 'SELECT * FROM users u LEFT JOIN orders o ...  -- сохранит всех users\nSELECT * FROM orders o LEFT JOIN users u ...  -- сохранит все orders',
  },

  // ── Типы JOIN ────────────────────────────────────────────────────────────────

  {
    id: 'join-8',
    difficulty: 'medium',
    question: 'Что возвращает FULL OUTER JOIN?',
    options: [
      'Все строки из обеих таблиц, NULL там где нет совпадения',
      'Только строки с совпадениями в обеих таблицах',
      'Все строки левой таблицы, NULL справа',
      'Декартово произведение всех строк',
    ],
    correct: 0,
    explanation: 'FULL OUTER JOIN = LEFT JOIN ∪ RIGHT JOIN. Сохраняет все строки из обеих таблиц. Колонки несовпавшей стороны — NULL. Редко используется на практике.',
    code: 'SELECT *\nFROM a\nFULL OUTER JOIN b ON a.id = b.a_id\n-- строки без пары из A: a.* + NULL для b\n-- строки без пары из B: NULL для a + b.*',
  },
  {
    id: 'join-9',
    difficulty: 'medium',
    question: 'Когда уместен SELF JOIN?',
    options: [
      'Когда строки одной таблицы ссылаются на другие строки той же таблицы',
      'Когда нужно объединить две одинаковые таблицы',
      'Когда обе таблицы содержат одни и те же данные',
      'SELF JOIN — ошибка синтаксиса в SQL',
    ],
    correct: 0,
    explanation: 'Классический пример SELF JOIN — таблица employees с колонкой manager_id, ссылающейся на id той же таблицы. JOIN соединяет сотрудника с его менеджером.',
    code: 'SELECT e.name, m.name AS manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.id',
  },
  {
    id: 'join-10',
    difficulty: 'easy',
    question: 'RIGHT JOIN — что он делает?',
    options: [
      'Сохраняет все строки правой таблицы, NULL для несовпавших слева',
      'Сохраняет все строки левой таблицы, NULL для несовпавших справа',
      'Возвращает только строки без совпадений',
      'Аналог INNER JOIN но с другим синтаксисом',
    ],
    correct: 0,
    explanation: 'RIGHT JOIN — зеркало LEFT JOIN. На практике почти не используется: A RIGHT JOIN B можно заменить на B LEFT JOIN A. Большинство команд придерживаются только LEFT JOIN для единообразия.',
    code: '-- Эти два запроса эквивалентны:\nSELECT * FROM a RIGHT JOIN b ON a.id = b.a_id\nSELECT * FROM b LEFT JOIN  a ON a.id = b.a_id',
  },

  // ── Синтаксис и нюансы ────────────────────────────────────────────────────────

  {
    id: 'join-11',
    difficulty: 'medium',
    question: 'Чем USING (dept_id) отличается от ON u.dept_id = d.id?',
    options: [
      'USING работает только если обе колонки называются одинаково и убирает дубликат из результата',
      'USING и ON идентичны, это просто разные синтаксисы',
      'USING медленнее ON',
      'USING запрещает NULL в join-колонке',
    ],
    correct: 0,
    explanation: 'USING (col) требует чтобы колонка называлась одинаково в обеих таблицах. В результате колонка появляется один раз (не дублируется). ON — более гибко, позволяет соединять разноимённые колонки.',
    code: 'SELECT * FROM users u JOIN departments d USING (dept_id)\n-- vs\nSELECT * FROM users u JOIN departments d ON u.dept_id = d.id',
  },
  {
    id: 'join-12',
    difficulty: 'hard',
    question: 'Что вернёт этот запрос для пользователей без заказов?',
    code: 'SELECT u.name, COUNT(*) AS cnt\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.name',
    options: [
      'cnt = 1 (NULL-строка от LEFT JOIN считается как одна строка)',
      'cnt = 0',
      'Пользователь не попадёт в результат',
      'Ошибка: нельзя GROUP BY с LEFT JOIN',
    ],
    correct: 0,
    explanation: 'COUNT(*) считает строки — а строка (с NULL справа) существует. Поэтому cnt = 1 даже при отсутствии заказов. Правильно: COUNT(o.id) — NULL не считается, вернёт 0.',
  },
  {
    id: 'join-13',
    difficulty: 'medium',
    question: 'Что произойдёт если JOIN-условие ON содержит NULL?',
    options: [
      'Строка не попадёт в результат — NULL != NULL',
      'NULL будет считаться равным NULL',
      'SQL вернёт ошибку',
      'Строка попадёт в результат с предупреждением',
    ],
    correct: 0,
    explanation: 'Условие NULL = NULL даёт UNKNOWN, что не равно TRUE. Поэтому строки с NULL в join-колонке не соединяются. Чтобы LEFT JOIN вернул такие строки, нужно использовать IS NULL отдельно.',
    code: 'SELECT * FROM users u\nLEFT JOIN departments d ON u.dept_id = d.id\n-- пользователь с dept_id = NULL не найдёт пару в departments\n-- но останется в результате с NULL справа (LEFT JOIN)',
  },
  {
    id: 'join-14',
    difficulty: 'hard',
    question: 'Почему этот запрос может вернуть неожиданно много строк?',
    code: 'SELECT u.name, o.product\nFROM users u\nJOIN orders o ON u.id = o.user_id',
    options: [
      'У одного пользователя может быть несколько заказов — строк будет столько, сколько заказов',
      'JOIN дублирует каждую строку',
      'JOIN работает только с уникальными ключами',
      'product — не уникальное поле, это вызывает дублирование',
    ],
    correct: 0,
    explanation: 'JOIN не "схлопывает" строки. Если у Alice 3 заказа — Alice появится 3 раза. Это называют "fan-out" (раздувание). Для агрегации нужен GROUP BY, а не просто JOIN.',
  },
  {
    id: 'join-15',
    difficulty: 'medium',
    question: 'Чем отличается WHERE от AND в условии JOIN?',
    code: '-- Вариант 1\nSELECT * FROM users u\nLEFT JOIN orders o ON u.id = o.user_id AND o.status = \'done\'\n\n-- Вариант 2\nSELECT * FROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE o.status = \'done\'',
    options: [
      'Вариант 1 сохранит пользователей без done-заказов (NULL), вариант 2 — нет',
      'Варианты идентичны',
      'Вариант 2 быстрее — WHERE фильтрует до JOIN',
      'Вариант 1 синтаксически некорректен',
    ],
    correct: 0,
    explanation: 'Условие в ON применяется ДО JOIN — для LEFT JOIN это значит: пробовать соединить только done-заказы, остальные строки users сохранить с NULL. WHERE применяется ПОСЛЕ JOIN и отфильтрует пользователей без done-заказов.',
  },
  {
    id: 'join-16',
    difficulty: 'hard',
    question: 'Что означает "неэквисоединение" (non-equi join)?',
    options: [
      'JOIN по условию, отличному от равенства: <, >, BETWEEN и т.д.',
      'JOIN таблиц с разным количеством строк',
      'JOIN без индекса — всегда Nested Loop',
      'Синоним CROSS JOIN',
    ],
    correct: 0,
    explanation: 'Неэквисоединение использует операторы !=, <, >, BETWEEN в условии ON. Пример: найти все пары (заказ, бонус) где сумма заказа попадает в диапазон бонуса.',
    code: 'SELECT o.id, b.discount\nFROM orders o\nJOIN bonus_tiers b ON o.amount BETWEEN b.min_amount AND b.max_amount',
  },

  // ── Производительность ────────────────────────────────────────────────────────

  {
    id: 'join-17',
    difficulty: 'hard',
    question: 'Почему важно иметь индекс на join-колонке?',
    options: [
      'Без индекса PostgreSQL делает Seq Scan второй таблицы для каждой строки первой',
      'Без индекса JOIN вернёт неправильный результат',
      'Без индекса JOIN недоступен — SQL выдаст ошибку',
      'Индекс нужен только для WHERE, на JOIN не влияет',
    ],
    correct: 0,
    explanation: 'Nested Loop Join: для каждой строки левой таблицы ищет соответствующую строку в правой. Без индекса — полный перебор (Seq Scan). С индексом — Index Scan за O(log n). Разница в 1000× на больших таблицах.',
    code: '-- После CREATE TABLE с FK добавь индекс:\nCREATE INDEX idx_orders_user_id ON orders (user_id);\n-- Иначе JOIN на 1M строк = 1M * Seq Scan',
  },
  {
    id: 'join-18',
    difficulty: 'medium',
    question: 'Что делает NATURAL JOIN и почему он опасен?',
    options: [
      'Соединяет по всем колонкам с одинаковыми именами — хрупко при изменении схемы',
      'Соединяет по PRIMARY KEY автоматически',
      'Работает только с FOREIGN KEY',
      'Синоним INNER JOIN ON id = id',
    ],
    correct: 0,
    explanation: 'NATURAL JOIN неявно соединяет по ВСЕМ колонкам с совпадающими именами. Добавишь колонку updated_at в обе таблицы — запрос начнёт давать неверные результаты. Лучше всегда явно указывать ON.',
    code: '-- Хрупко:\nSELECT * FROM users NATURAL JOIN departments\n-- Надёжно:\nSELECT * FROM users u JOIN departments d ON u.dept_id = d.id',
  },
  {
    id: 'join-19',
    difficulty: 'medium',
    question: 'Что произойдёт при SELECT * FROM users JOIN departments без условия ON?',
    options: [
      'Синтаксическая ошибка или CROSS JOIN в зависимости от СУБД',
      'INNER JOIN по всем совпадающим колонкам',
      'Результат только первой таблицы',
      'NULL для всех колонок второй таблицы',
    ],
    correct: 0,
    explanation: 'В PostgreSQL JOIN без ON — синтаксическая ошибка для INNER/LEFT JOIN. Без условия нужно явно написать CROSS JOIN. Это избегает случайного декартова произведения.',
    code: '',
  },
  {
    id: 'join-20',
    difficulty: 'hard',
    question: 'Пользователь "Henry" есть в users но нет в orders. Что вернёт запрос?',
    code: 'SELECT u.name, SUM(o.amount) AS total\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.name\nORDER BY total DESC',
    options: [
      'Henry появится в результате с total = NULL',
      'Henry не появится — нет заказов',
      'Henry появится с total = 0',
      'Ошибка: SUM не работает с NULL',
    ],
    correct: 0,
    explanation: 'LEFT JOIN сохранит Henry с NULL в колонках orders. SUM(NULL) = NULL, а не 0. Чтобы получить 0 — нужен COALESCE: COALESCE(SUM(o.amount), 0).',
  },
  {
    id: 'join-21',
    difficulty: 'medium',
    question: 'Что значит "ambiguous column" ошибка в JOIN-запросе?',
    options: [
      'Колонка с таким именем есть в обеих таблицах — нужно указать алиас таблицы',
      'Колонка содержит NULL-значения',
      'Колонка не проиндексирована',
      'Нельзя использовать эту колонку в WHERE',
    ],
    correct: 0,
    explanation: 'ERROR: column "id" is ambiguous — обе таблицы содержат колонку id. PostgreSQL не знает какую взять. Решение: u.id или o.id с явным алиасом таблицы. Хорошая практика: всегда указывай алиас в JOIN-запросах.',
    code: 'SELECT id FROM users u JOIN orders o ...    -- ERROR\nSELECT u.id FROM users u JOIN orders o ...  -- OK',
  },
  {
    id: 'join-22',
    difficulty: 'hard',
    question: 'В чём проблема этого запроса для подсчёта среднего?',
    code: 'SELECT d.title, AVG(u.salary) AS avg_sal\nFROM departments d\nLEFT JOIN users u ON u.dept_id = d.id\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY d.title',
    options: [
      'Дублирование строк users через orders искажает AVG — сотрудники с несколькими заказами считаются несколько раз',
      'LEFT JOIN нельзя использовать дважды',
      'AVG не работает с NULL',
      'Запрос корректен — AVG всегда правильный',
    ],
    correct: 0,
    explanation: 'Alice с 2 заказами будет в результате 2 раза. AVG(salary) посчитает её зарплату дважды — результат неверный. Решение: сначала агрегировать заказы в подзапросе или CTE, потом JOIN.',
  },
];
