import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'n1',
    difficulty: 'easy',
    question: 'На каком языке программирования основан NestJS?',
    options: ['JavaScript', 'TypeScript', 'Python', 'Go'],
    correct: 1,
    explanation: 'NestJS построен на TypeScript. Это обеспечивает строгую типизацию, декораторы и современные возможности ООП «из коробки».',
  },
  {
    id: 'n2',
    difficulty: 'easy',
    question: 'Какая команда устанавливает Nest CLI глобально?',
    options: [
      'npm install @nestjs/cli',
      'npm install -g @nestjs/cli',
      'nest install global',
      'npx create-nest-app',
    ],
    correct: 1,
    explanation: 'Флаг -g устанавливает пакет глобально. После этого команда nest станет доступна в любой директории.',
  },
  {
    id: 'n3',
    difficulty: 'easy',
    question: 'Как создать новое NestJS приложение через CLI?',
    options: [
      'nest start myapp',
      'nest new myapp',
      'nest create myapp',
      'nest init myapp',
    ],
    correct: 1,
    explanation: 'Команда nest new создаёт новый проект: генерирует структуру папок, файлы конфигурации и устанавливает зависимости.',
  },
  {
    id: 'n4',
    difficulty: 'easy',
    question: 'На каком порту по умолчанию запускается NestJS приложение?',
    options: ['8080', '4000', '3000', '5000'],
    correct: 2,
    explanation: 'По умолчанию NestJS слушает порт 3000. Это указано в main.ts: app.listen(process.env.PORT ?? 3000).',
  },
  {
    id: 'n5',
    difficulty: 'easy',
    question: 'Что такое модуль в NestJS?',
    options: [
      'Файл конфигурации TypeScript',
      'Класс с декоратором @Module, который группирует компоненты по функциональности',
      'Отдельный микросервис',
      'Функция для обработки ошибок',
    ],
    correct: 1,
    explanation: 'Модуль — это контейнер, который группирует контроллеры, сервисы и другие модули для решения конкретной задачи (например, UserModule, AuthModule).',
  },
  {
    id: 'n6',
    difficulty: 'medium',
    question: 'Какая роль у контроллера в NestJS?',
    options: [
      'Хранить бизнес-логику приложения',
      'Работать напрямую с базой данных',
      'Принимать HTTP-запросы и делегировать обработку сервису',
      'Настраивать зависимости между модулями',
    ],
    correct: 2,
    explanation: 'Контроллер только маршрутизирует запросы — принимает их и передаёт в нужный сервис. Никакой бизнес-логики: её место в сервисах.',
  },
  {
    id: 'n7',
    difficulty: 'medium',
    question: 'Какой декоратор делает класс сервисом, доступным для инъекции зависимостей?',
    options: ['@Service()', '@Injectable()', '@Provider()', '@Singleton()'],
    correct: 1,
    explanation: '@Injectable() сообщает системе IoC контейнера NestJS, что этот класс может быть создан и инъецирован в другие классы.',
  },
  {
    id: 'n8',
    difficulty: 'medium',
    question: 'Где хранится вся бизнес-логика в NestJS?',
    options: ['В контроллерах', 'В модулях', 'В сервисах', 'В main.ts'],
    correct: 2,
    explanation: 'Сервисы — мозг приложения. Они работают с базой данных, проверяют данные, обрабатывают ошибки. Контроллер лишь передаёт запрос — сервис решает что делать.',
  },
  {
    id: 'n9',
    difficulty: 'medium',
    question: 'Что происходит с TaskModule, когда его добавляют в imports AppModule?',
    options: [
      'Модуль перезаписывает AppModule',
      'Контроллеры и сервисы TaskModule становятся доступны в приложении',
      'Создаётся отдельный сервер для Task',
      'Ничего — это лишь организационная метка',
    ],
    correct: 1,
    explanation: 'Импорт модуля регистрирует его контроллеры в роутере и делает сервисы доступными для инъекции. Приложение «расширяется» функциональностью этого модуля.',
  },
  {
    id: 'n10',
    difficulty: 'medium',
    question: 'Какую команду запускает режим watch (автоперезагрузка)?',
    options: ['yarn start', 'yarn start:prod', 'yarn start:dev', 'yarn run build'],
    correct: 2,
    explanation: 'yarn start:dev запускает приложение в режиме разработки с hot-reload: при изменении файлов сервер автоматически перезапускается.',
  },
  {
    id: 'n11',
    difficulty: 'medium',
    question: 'Какой файл является точкой входа NestJS приложения?',
    options: ['app.module.ts', 'app.controller.ts', 'nest-cli.json', 'main.ts'],
    correct: 3,
    explanation: 'main.ts — точка запуска. Здесь вызывается NestFactory.create(AppModule) и app.listen(). Остальные файлы — компоненты приложения.',
  },
  {
    id: 'n12',
    difficulty: 'medium',
    question: 'Что делает декоратор @Controller("task") над классом?',
    options: [
      'Регистрирует сервис с префиксом "task"',
      'Устанавливает базовый путь /task для всех маршрутов этого контроллера',
      'Создаёт модуль task',
      'Помечает класс как middleware',
    ],
    correct: 1,
    explanation: '@Controller("task") задаёт базовый путь. Если внутри описать @Get("all"), полный путь будет /task/all.',
  },
  {
    id: 'n13',
    difficulty: 'hard',
    question: 'Как NestJS внедряет TaskService в TaskController?',
    options: [
      'Через глобальную переменную',
      'Через конструктор с параметром private readonly taskService: TaskService',
      'Через import в TypeScript',
      'Через декоратор @Inject на методе',
    ],
    correct: 1,
    explanation: 'Это Dependency Injection (DI). NestJS читает типы параметров конструктора и автоматически создаёт и передаёт нужные экземпляры. Ключевое слово readonly — хорошая практика.',
  },
  {
    id: 'n14',
    difficulty: 'hard',
    question: 'Что хранится в nest-cli.json?',
    options: [
      'Список установленных пакетов',
      'Настройки приложения: sourceRoot, компилятор, плагины',
      'Переменные окружения',
      'TypeScript конфигурация',
    ],
    correct: 1,
    explanation: 'nest-cli.json конфигурирует CLI: где искать исходники, какой компилятор использовать (tsc или swc), какие плагины подключать (например для Swagger).',
  },
  {
    id: 'n15',
    difficulty: 'hard',
    question: 'Зачем нужен AppModule — нельзя ли просто подключить все контроллеры в main.ts?',
    options: [
      'Можно, AppModule — просто соглашение по именованию',
      'Нельзя: NestFactory.create принимает только один корневой модуль, а он объединяет все остальные',
      'AppModule нужен только для деплоя в продакшн',
      'AppModule обязателен только при использовании TypeORM',
    ],
    correct: 1,
    explanation: 'NestJS строит граф зависимостей из модульной иерархии. AppModule — корень дерева. Все остальные модули (UserModule, TaskModule) импортируются в него, образуя единую управляемую систему.',
  },
];
